#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENV_DIR="${DARTS_DEVEL_VENV:-$ROOT_DIR/build/devel-venv}"
PYTHON_BIN="${PYTHON_BIN:-python3}"
TORCH_SPEC="${DARTS_TORCH_SPEC:-torch>=2.7}"
TORCH_INDEX_URL="${DARTS_TORCH_INDEX_URL:-}"
INSTALL_TORCH=1
INSTALL_PROJECT=1

usage() {
  cat <<'EOF'
Usage: scripts/bootstrap_devel_env.sh [options]

Options:
  --venv PATH              Development virtualenv (default: build/devel-venv)
  --python PATH            Python interpreter used to create it
  --torch-spec SPEC        PyTorch requirement (default: torch>=2.7)
  --torch-index-url URL    Official PyTorch wheel index matching the GPU
  --no-torch               Do not install PyTorch; it must already be present
  --no-install-project     Prepare dependencies without installing darts
  -h, --help               Show this help

The script prepares one environment for Meson/Cython, C++ dependencies,
Python tests, neural training and ONNX export. It writes build/devel-env.sh;
source that file before invoking Meson, pip builds or training commands.
EOF
}

while (($#)); do
  case "$1" in
    --venv)
      VENV_DIR="$2"
      shift 2
      ;;
    --python)
      PYTHON_BIN="$2"
      shift 2
      ;;
    --torch-spec)
      TORCH_SPEC="$2"
      shift 2
      ;;
    --torch-index-url)
      TORCH_INDEX_URL="$2"
      shift 2
      ;;
    --no-torch)
      INSTALL_TORCH=0
      shift
      ;;
    --no-install-project)
      INSTALL_PROJECT=0
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

mkdir -p "$(dirname "$VENV_DIR")"
if [[ ! -x "$VENV_DIR/bin/python" ]]; then
  "$PYTHON_BIN" -m venv "$VENV_DIR"
fi

PIP="$VENV_DIR/bin/pip"
"$PIP" install --upgrade pip
if ((INSTALL_TORCH)); then
  torch_args=(install "$TORCH_SPEC")
  if [[ -n "$TORCH_INDEX_URL" ]]; then
    torch_args+=(--index-url "$TORCH_INDEX_URL")
  fi
  "$PIP" "${torch_args[@]}"
  "$PIP" install -r "$ROOT_DIR/requirements/devel.txt"
else
  "$PIP" install \
    -r "$ROOT_DIR/requirements/build.txt" \
    -r "$ROOT_DIR/requirements/train-common.txt"
fi

export DARTS_DEPS_DIR="${DARTS_DEPS_DIR:-$ROOT_DIR/build/deps}"
DARTS_ONNXRUNTIME_DIR="$("$ROOT_DIR/scripts/fetch_onnxruntime.sh")"
export DARTS_ONNXRUNTIME_DIR
"$ROOT_DIR/scripts/bootstrap_local_deps.sh" >/dev/null
export DARTS_MESON_BUILD_DIR="${DARTS_MESON_BUILD_DIR:-$ROOT_DIR/build/meson-devel}"

ENV_FILE="$ROOT_DIR/build/devel-env.sh"
{
  printf '# Generated by scripts/bootstrap_devel_env.sh\n'
  printf 'export DARTS_ROOT=%q\n' "$ROOT_DIR"
  printf 'export DARTS_DEVEL_VENV=%q\n' "$VENV_DIR"
  printf 'export DARTS_DEPS_DIR=%q\n' "$DARTS_DEPS_DIR"
  printf 'export DARTS_ONNXRUNTIME_DIR=%q\n' "$DARTS_ONNXRUNTIME_DIR"
  printf 'export DARTS_MESON_BUILD_DIR=%q\n' "$DARTS_MESON_BUILD_DIR"
  printf 'export PATH=%q:$PATH\n' "$VENV_DIR/bin"
} >"$ENV_FILE"

if ((INSTALL_PROJECT)); then
  "$PIP" install --no-deps --no-build-isolation --force-reinstall "$ROOT_DIR/python"
fi

if ((INSTALL_PROJECT)); then
  "$VENV_DIR/bin/python" -c 'import darts; print(f"darts={darts.__file__}")'
fi
if "$VENV_DIR/bin/python" -c 'import torch' >/dev/null 2>&1; then
  "$VENV_DIR/bin/python" -c \
    'import torch; print(f"torch={torch.__version__} cuda={torch.cuda.is_available()}")'
fi
echo "environment=$ENV_FILE"
echo "activate=source $ENV_FILE"
